steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/otel-go-example/main:latest', '.']
images: ['us-central1-docker.pkg.dev/$PROJECT_ID/otel-go-example/main:latest']
options:
  sourceProvenanceHash: ['SHA256']
  requestedVerifyOption: VERIFIED
