apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-go-example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: otel-go-example
  template:
    metadata:
      labels:
        app: otel-go-example
    spec:
      containers:
      - name: otel-go-example
        image: us-central1-docker.pkg.dev/cco-in-context-test/otel-go-example/main@sha256:9e80ce67e15c456b8890c8b67aed32bcfe727e55df0e3c0faf8eb6ab58fa3927
        ports:
        - containerPort: 8080
          name: "http"
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /rolldice
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
